# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    pubspec = YAML.load_file("../../pubspec.yaml")
    build_number = latest_testflight_build_number + 1
    version_string = "#{pubspec["version"]} (#{build_number})"
    UI.message("Building #{pubspec["name"]} #{version_string}")

    sh(
      "flutter", "build", "ipa",
      "--obfuscate",
      "--split-debug-info=debug-info",
      "--release",
      "--build-number=#{build_number}",
    )
    upload_to_testflight(
      ipa: ipaPath,
      skip_waiting_for_build_processing: ENV['CI'],
    )
  end

  def ipaPath
    name = get_info_plist_value(path: "./Runner/Info.plist", key: "CFBundleName")
    return "../build/ios/ipa/#{name}.ipa"
  end
end
